# Generated by Django 4.1.1 on 2022-09-08 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapi', '0004_alter_product_picture1_alter_product_picture2'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Returned', 'Returned')], default='Delivered', max_length=10),
        ),
    ]
