# Generated by Django 4.1.1 on 2022-09-08 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapi', '0011_alter_order_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
    ]
